[package]
name = "rust-edrum-waver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.2.7", features = ["derive"] }
color-eyre = "0.6.2"
crossterm = { version = "0.26.1", features = ["serde"] }
csv = "1.2.1"
lazy_static = "1.4.0"
log = "0.4.17"
playback-rs = "0.4.2"
pretty_env_logger = "0.4.0"
rodio = "0.17.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sevenz-rust = "0.2.10"
thiserror = "1.0.40"
tui = { version = "0.19.0", default-features = false, features = ["crossterm", "serde"] }

[dev-dependencies]
simplelog = "0.12"
