[package]
name = "rust-edrum-waver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
crossterm = "0.26.1"
csv = "1.2.1"
log = "0.4.17"
rodio = "0.17.1"
serde = { version = "1.0.163", features = ["derive"] }
sevenz-rust = "0.2.10"
slint = "1.0.2"

[build-dependencies]
slint-build = "1.0.2"