name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ectobit/reusable-workflows/.github/workflows/rust-check.yaml@main
    runs-on: windows-latest

  build:
    runs-on: windows-latest
    needs: check

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/cargo@v1
        with:
          version: stable

      - name: Build application
        run: cargo build --release

      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "drum_weaver").version')

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: target/release/my_app.exe
