name: Build and Release

on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/cargo@v1
        with:
          version: stable

      - name: Build application
        run: cargo build --release

      - name: Get version
        id: version
        run: echo "::set-output name=VERSION::$(cat VERSION)"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: target/release/my_app.exe
