name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get version
        id: version
        run: echo "::set-output name=VERSION::$(cat VERSION)"

      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.4.0

      - name: Set up Rust
        uses: actions-rs/cargo@v1
        with:
          version: stable

      - name: Build application
        run: cargo build --release

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: DrumWeaver
          path: target/release/drum_weaver.exe
